### ISSUE TITLE
Totp extention

### ISSUE THREAD

**Issue by maxoulamenasse** [tschoonj/guacamole_exporter#9]
Hi ! 
First of all, I would like to thank you for your wonderfull exporter !
How can I implement you guacamole_exporter when my Apache Guacamole is configured with TOTP extention and/or LDAP extension ?

Thank you !

**Comment by tschoonj** [comment]
This exporter works by using the Guacamole REST API, which requires that you login using a JSON payload containing username and password to get a token, which must be used for subsequent interaction with the server.

I doubt that this will work nicely with TOTP, but should work with LDAP (but not when combined with TOTP!), which I assume you are using for both authentication and authorization. In this case you would need to set `GUACAMOLE_DATASOURCE` to "ldap".

I use this exporter on a Guacamole instance that uses LDAP for authentication, and mysql for authorization, and this works fine.

**Comment by maxoulamenasse** [comment]
Ok thanks, I will try to remove TOTP extension and let LDAP onyl for authentification works with the exporter ;)

Regards,
